###
###  Android
###

platform :android do

  desc "Pull Request verification"
  lane :pull_request_verification do
    gradle(project_dir: "android", task: "clean lintDebug test")
    gradle(project_dir: "android", task: "app:assembleDebug")
  end

  desc "Deploy current code to stage"
  lane :deploy_to_stage do
    gradle(project_dir: "android", task: "assemble")
    gradle(project_dir: "android", task: "uploadArchives --no-daemon --no-parallel")
    gradle(project_dir: "android", task: "closeAndReleaseRepository")
  end

  desc "Deploy current code to production"
  lane :deploy_to_production do
    sh "bash ./release/maven_signing.sh"
    deploy_to_stage
  end
end

###
###  Backend
###

platform :backend do

  desc "Deploy current code to stage"
  lane :deploy_to_stage do
    gradle(project_dir: "backend", task: "assemble")
    gradle(project_dir: "backend", task: "uploadArchives --no-daemon --no-parallel")
    gradle(project_dir: "backend", task: "closeAndReleaseRepository")
  end

  desc "Deploy current code to production"
  lane :deploy_to_production do
    sh "bash ./release/maven_signing.sh"
    deploy_to_stage
  end
end