#
# Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Backend Pull Request

on:
    pull_request:
        branches:
            - master
        paths:
            - "backend/**"

jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup JDK 11
            - run: echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV
            - name: Install gem dependencies
            - run: bundle install
            - name: Run pr check
            - run: bundle exec fastlane backend pull_request_verification
