name: Android Pull Request

on:
  pull_request:
    paths:
      - 'android/**'

jobs:
    pr-verification:
        name: PR Check
        runs-on: macos-latest
        steps:
            -   name: Install gem dependencies
                run: bundle install
            -   name: Run pr check
                run: bundle exec fastlane android pull_request_verification