name: Backend Pull Request

on:
    pull_request:
        branches: 
            - master
        paths:
            - 'backend/**'
            
jobs:
    pr-verification:
        name: PR Check
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                
            -   name: Setup JDK 11
                run: echo "JAVA_HOME=$JAVA_HOME_11_X64" >> $GITHUB_ENV

            -   uses: actions/checkout@v2
            -   name: Install gem dependencies

                run: bundle install
            -   name: Run pr check
                run: bundle exec fastlane backend pull_request_verification
